### ISSUE TITLE
RuntimeError: application not registered on db instance

### ISSUE THREAD

**Issue by heyjordn** [sholsapp/flask-rrd#1]
Whenever I try to start the webserver with `manage.py runsever`, I get this error

```
/home/proxima/Desktop/flask-rrd/venv/lib/python2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.script is deprecated, use flask_script instead.
  .format(x=modname), ExtDeprecationWarning
/home/proxima/Desktop/flask-rrd/venv/lib/python2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.bootstrap is deprecated, use flask_bootstrap instead.
  .format(x=modname), ExtDeprecationWarning
/home/proxima/Desktop/flask-rrd/venv/lib/python2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.restless is deprecated, use flask_restless instead.
  .format(x=modname), ExtDeprecationWarning
/home/proxima/Desktop/flask-rrd/venv/lib/python2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
  .format(x=modname), ExtDeprecationWarning
Traceback (most recent call last):
  File "./manage.py", line 13, in <module>
    from flaskrrd import app, init_webapp
  File "/home/proxima/Desktop/flask-rrd/flaskrrd/__init__.py", line 21, in <module>
    manager.create_api(RRD, methods=['GET', 'POST'])
  File "/home/proxima/Desktop/flask-rrd/venv/lib/python2.7/site-packages/Flask_Restless-0.17.0-py2.7.egg/flask_restless/manager.py", line 698, in create_api
    blueprint = self.create_api_blueprint(app=app, *args, **kw)
  File "/home/proxima/Desktop/flask-rrd/venv/lib/python2.7/site-packages/Flask_Restless-0.17.0-py2.7.egg/flask_restless/manager.py", line 566, in create_api_blueprint
    pk_name = primary_key or primary_key_name(model)
  File "/home/proxima/Desktop/flask-rrd/venv/lib/python2.7/site-packages/Flask_Restless-0.17.0-py2.7.egg/flask_restless/helpers.py", line 232, in primary_key_name
    pk_names = primary_key_names(model)
  File "/home/proxima/Desktop/flask-rrd/venv/lib/python2.7/site-packages/Flask_Restless-0.17.0-py2.7.egg/flask_restless/helpers.py", line 214, in primary_key_names
    return [key for key, field in inspect.getmembers(model)
  File "/usr/lib64/python2.7/inspect.py", line 253, in getmembers
    value = getattr(object, key)
  File "/home/proxima/Desktop/flask-rrd/venv/lib/python2.7/site-packages/Flask_SQLAlchemy-2.1-py2.7.egg/flask_sqlalchemy/__init__.py", line 500, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/scoping.py", line 78, in __call__
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/_collections.py", line 990, in __call__
  File "/home/proxima/Desktop/flask-rrd/venv/lib/python2.7/site-packages/Flask_SQLAlchemy-2.1-py2.7.egg/flask_sqlalchemy/__init__.py", line 771, in create_session
    return SignallingSession(self, **options)
  File "/home/proxima/Desktop/flask-rrd/venv/lib/python2.7/site-packages/Flask_SQLAlchemy-2.1-py2.7.egg/flask_sqlalchemy/__init__.py", line 153, in __init__
    self.app = app = db.get_app()
  File "/home/proxima/Desktop/flask-rrd/venv/lib/python2.7/site-packages/Flask_SQLAlchemy-2.1-py2.7.egg/flask_sqlalchemy/__init__.py", line 922, in get_app
    raise RuntimeError('application not registered on db '
RuntimeError: application not registered on db instance and no application bound to current context
```

Any ideas on how to fix?

OS: Arch Linux 4.6

**Comment by sholsapp** [comment]
Hey @Pr0x1m4, I'm not sure how this bug snuck past my own environment, but I fixed the code in my last commit. I also pinned all the dependencies I tested with so you can try and reproduce. Should work now. Thanks for opening an issue.

**Comment by heyjordn** [comment]
Hey man, it happens lol, thanks a tonne it works fine now
![2016-07-05-115743_1920x1080_scrot](https://cloud.githubusercontent.com/assets/4820517/16592849/3e4db8c0-42a8-11e6-8b20-0c96609e6ce8.png)

**Comment by sholsapp** [comment]
Okay, let me know if anything else acts strangely. 😄
