### ISSUE TITLE
Server breaks on rrd_update

### ISSUE THREAD

**Issue by heyjordn** [sholsapp/flask-rrd#2]
While server is running and I try to run `manage.py update_rrd`, the server outputs this

``` python
ERROR:flaskrrd:Exception on /update/test [POST]
Traceback (most recent call last):
  File "/home/proxima/Desktop/Code/PYTHON/flask-rrd/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/proxima/Desktop/Code/PYTHON/flask-rrd/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/proxima/Desktop/Code/PYTHON/flask-rrd/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/proxima/Desktop/Code/PYTHON/flask-rrd/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/proxima/Desktop/Code/PYTHON/flask-rrd/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/proxima/Desktop/Code/PYTHON/flask-rrd/flaskrrd/__init__.py", line 155, in update
    if create_rrd(rrd, desc):
  File "/home/proxima/Desktop/Code/PYTHON/flask-rrd/flaskrrd/__init__.py", line 114, in create_rrd
    for ds_type in description['metrics']:
KeyError: 'metrics'

```

**Comment by sholsapp** [comment]
Fixed - that was a old testing function I hadn't updated when I changed the API awhile back. I've updated it to use the new API. The scripts in bin/ are all valid.

**Comment by heyjordn** [comment]
I was just about to put in a pull request for this, you beat me to it lol
